name: "Codegen and Test"
description: "Run go generate, go vet, and go test"
runs:
  using: "composite"
  steps:
    - run: go generate ./...
      shell: bash
    - run: go vet ./...
      shell: bash
    - run: go test -race ./...
      shell: bash
